name: consume_api
description: Consumindo API com Flutter.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
